import Head from 'next/head'
import Hero from '../../comp/Hero/Hero'
import Menu from '../../comp/Menu/Menu'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <Hero />  
    </div>
  )
}
