import Head from 'next/head'
import Short from '../../comp/About/short'
import Cta from '../../comp/CTA/Cta'
import Heroes from '../../comp/Grid/Heroes'
import Hero from '../../comp/Hero/Hero'
import Menu from '../../comp/Menu/Menu'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Home - Georgian Liberty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <Hero />  
      <Short />
      <Cta />
      {/* <Heroes /> */}
    </div>
  )
}
